server:
  port: 8760

spring:
  application:
    name: API-GATEWAY
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # 새로 추가한 옵션 Entity Class 기반으로 Table 생성
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rev_problem?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root

zuul:
  routes:
    PROBLEM-SERVICE:
      path: /problem/**
      serviceId: PROBLEM-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost